<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://servicios" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://servicios" xmlns:intf="http://servicios" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://servicios" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="mostrarMorososMatricula">
    <complexType/>
   </element>
   <element name="mostrarMorososMatriculaResponse">
    <complexType>
     <sequence>
      <element name="mostrarMorososMatriculaReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="mostrarMorososMatriculaResponse">

      <wsdl:part element="impl:mostrarMorososMatriculaResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="mostrarMorososMatriculaRequest">

      <wsdl:part element="impl:mostrarMorososMatricula" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="ServicioMatricula">

      <wsdl:operation name="mostrarMorososMatricula">

         <wsdl:input message="impl:mostrarMorososMatriculaRequest" name="mostrarMorososMatriculaRequest">

       </wsdl:input>

         <wsdl:output message="impl:mostrarMorososMatriculaResponse" name="mostrarMorososMatriculaResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="ServicioMatriculaSoapBinding" type="impl:ServicioMatricula">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="mostrarMorososMatricula">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="mostrarMorososMatriculaRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="mostrarMorososMatriculaResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="ServicioMatriculaService">

      <wsdl:port binding="impl:ServicioMatriculaSoapBinding" name="ServicioMatricula">

         <wsdlsoap:address location="http://localhost:8080/ServicioUniver/services/ServicioMatricula"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
